version: '2'
services:
  web:
    build: .
    restart: always
  lb:
    restart: always
    image: dockercloud/haproxy
    links:
     - web
    ports:
     - '8080:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
